---
# Connection settings for docker host
ansible_host: "{{ docker_pve2_ip }}"
ansible_user: dockeruser

# USB backup drive configuration for Zerobyte
backup_drive_uuid: "1835a880-5494-4a9b-8606-0b6c18e5b803"
