$ANSIBLE_VAULT;1.1;AES256
38616131343862663465663461313237363435613039373166623132383131626530633164303232
6433656531303836353636653939346339393834316239640a636166343161346362313535353536
64386534623137633636633833636461623261626565353161353263653633386332653138636231
3036343030313162660a333764323138363031323132633739613538653536646562373738663966
33303238653231373064653333386434346463616137623933346638353764316364373038336132
62656539653266653262383030373336656431306562363239626437353438306634323263633462
66393034666430613237613136326663356132663331633639346334376536366263313935313636
63613363643630323036643834623463343631343436336434313561616634323366623962366361
35656262663730353130356464366131333962333134323331656364306430613262616539323730
31306533663732333534383931366264303737393566333166366233633434643739393030356634
30316665306565666131393166346234663235343036316266346433623834306239393935666561
31393339306431343964656565373738316136356238616462346530653636626465616335656137
61383761393664363165373430363735633037663265386337353832656166353332356363316634
63363365376663643433363164303939393862366665316430363662633764376138353533646265
31643438396635626261623032313162313261656239363131313565633933626265333236656266
34313264623733346535623333303466323066636234663765346430376137616366666532373961
34623530303563643961623966333138376664346537313963383736336162643335353862383966
38373965356664663935323864323131663861636334616436633035356265373937326336396464
63633062636638386561373136626565336234646337636562356237353434623035633337386266
61366134663237343165336364633934373939376462643038393864333133663165646563613561
32623366376239616561323739656263646163613861653762313532633332663031623535396433
3765646464303834343736636139356234313032396631363034
